sabia/app/cliente/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from .views import estadoPedido

from django.contrib.auth.views import LoginView


urlpatterns = [
    path('register/', views.register, name='register_cliente'),
    path('', views.login, name="login_cliente"),
    path('', views.logouts, name="logout_cliente"),
#-----------------------modulos de cliente -------------

#-----------------------Pedido Estado :  cliente -------------
    url('estado_pedido', views.estadoPedido, name='estado_pedido'),


]

sabia/sabia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.home.urls')),
    path('usuario/',  include('app.usuario.urls')),
    path('denuncias/',  include('app.denuncias.urls')),
    path('adopciones/',  include('app.adopciones.urls')),
    path('donaciones/',  include('app.donaciones.urls')),
    path('blogs/',  include('app.blogs.urls')),
    url(r'paypal/', include('paypal.standard.ipn.urls')),
    url(r'payment/',include('app.payment.urls')),
    url('servicios/', include('app.servicios.urls')),
    url(r'^cart/', include('app.cart.urls')),
    url(r'orders/', include('app.orders.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #-----------------cliente
    url('cliente/', include('app.cliente.urls')),
    path('reportes/', include('app.reports.urls')),
    path('i18n/', include("django.conf.urls.i18n")),
    path('',include('pwa.urls')),
    #--------------------reseteo--------------------------------------
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="cliente/admin_cliente/registration/password_reset_form.html",email_template_name="cliente/admin_cliente/registration/password_reset_email.html"),
         name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(template_name="cliente/admin_cliente/registration/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="cliente/admin_cliente/registration/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="cliente/admin_cliente/registration/password_reset_complete.html"), name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sabia/app/cliente/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict
from django.contrib.auth.models import User

class Client(models.Model):
    username = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=10)
    first_name = models.CharField(max_length=150,verbose_name='Nombres')
    last_name = models.CharField(max_length=150, verbose_name='Apellidos')
    email = models.EmailField()
    telefono = models.IntegerField()
    User = models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.username


    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['id']

sabia/app/home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.forms import model_to_dict


class Contactos(models.Model):
    nombres = models.CharField(max_length=50, blank=True, verbose_name='Nombres')
    apellidos = models.CharField(max_length=50, blank=True, verbose_name='Apellidos')
    email =models.EmailField(blank=True,verbose_name="Email")
    telefono = models.CharField(max_length=10,blank=True, verbose_name="Telefono")
    direccion= models.CharField(max_length=100,blank=True, verbose_name="Direccion")
    estado = models.BooleanField(default=False)
    descripcion = models.TextField(blank=True, verbose_name='Descripcion')



    def toJSON(self):
            item = model_to_dict(self,exclude='estado')
            return item

    class Meta:
        ordering = ['id']

sabia/app/cliente/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth.models import User

sabia/app/cliente/views.py
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
from django.contrib import messages
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import Client
from django.views.generic import ListView, DetailView, UpdateView, TemplateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages

from ..orders.models import Order, OrderItem
from ..orders.views import OrderDetail
from ..usuario.models import Perfil


def login(request):
    if request.session.get('id') != None:  # Puede iniciar sesión solo cuando no haya iniciado sesión
        messages.success(request, "Bienvenido")
        return redirect('product_list')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            username = username.strip()            # Eliminar espacios y líneas nuevas
            password = password.strip()
            try:
                user = Client.objects.get(username=username)
            except:
                messages.success(request, "Nombre de Usuario no Existe ")
                return render(request, 'cliente/login.html')
            if user.password == password:
                request.session['id'] = user.id    # Registrar que el usuario ha iniciado sesión
                messages.success(request, "Bienvenido"+user.username)
                return redirect('product_list')
            else:
                messages.success(request, "contraseña Incorecta" )
                return render(request, 'cliente/login.html')
    return render(request, 'cliente/login.html')


def register(request):

    messages.success(request, "Cierra tu Cuenta primero ")
    if request.session.get('id') != None:  # Regístrese solo cuando no haya iniciado sesión
        return redirect('product_list')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        telefono = request.POST.get('telefono')
        username = username.strip()  # Eliminar espacios y líneas nuevas
        password = password.strip()
        if Client.objects.filter(username=username).exists():
            messages.success(request, "Cliente Registrado")
            return render(request, 'cliente/login.html')
        user = Client()
        user.username = username
        user.password = password
        user.email = email
        user.telefono = telefono
        user.save()
        request.session['id'] = user.id   # Registrar que el usuario ha iniciado sesión
        messages.success(request, "Cliente Registrado")
        return redirect('register_cliente')


    return render(request, 'cliente/register.html')


def logouts(request):
    request.session.flush()
    messages.success(request, "ssss")
    return redirect('product_list')




@csrf_exempt
def estadoPedido(request):
    user = Perfil()
    model = OrderItem

    if request.session.get('order_id') :
        order_id = request.session.get('order_id')
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'cliente/admin_cliente/estado_pedido.html',{'order':order})


    else :

        order = OrderItem.objects.all().order_by('id')
        return render(request, 'cliente/admin_cliente/estado_pedido.html',{'order':order})


class Listado_Order1(SuccessMessageMixin, ListView):
    model = Order
    template_name = 'cliente/admin_cliente/estado_pedido.html'

    def get_context_data(self, **kwargs):
        context = super(Listado_Order1, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        usuario = User.objects.get(id=pk)
        perfil = Perfil.objects.get(User_id=usuario.id)
        order = Order.objects.all().order_by('id')
        return {'usuario': usuario, 'perfil': perfil,'order':order}

sabia/templates/cliente/login.html
{% extends "base/base.html" %}
{% block titulo %} Login -Cliente {% endblock %}



{% block contenido %}



<div class="container">

       <div class="col-md-4 col-md-offset-4">
  <form   method="post">
            {% csrf_token %}
   <div class="form-group">
 <label > Nombre de usuario: </label>
 <input type="text" name='username' class="form-control"  placeholder="Username" autofocus required>

   </div>
      <div class="form-group">
            <label> Contraseña: </label>

    <input type="password" name='password' class="form-control"  placeholder="Password" required>

      </div>
          <button type = "submit" class = "btn btn-primary pull-right"> Enviar </button>

        </form>
</div>
</div>
{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
              title: 'Inicio Cliente',
              text: '{{m}}',
              icon: 'info',
              confirmButtonText: 'Ok'
})
        </script>
    {% endfor %}
{% endif %}

{% endblock %}

sabia/templates/cliente/perfil_cliente.html
<!-- carga los archivos estaticos  -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/ab00d86059.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'logins.css' %}">
    <title>Registro</title>
    <link href="{% static 'css/perro.css' %}" rel="stylesheet">
</head>



<body>
 <div class="container" >

    <div class="forms-container">
      <div class="signin-signup">

        <form method="post", enctype="multipart/form-data"  class="sign-in-form">
                        {% csrf_token %}

          <h2 class="title">Registrar 2/2 </h2>
    <p>



     <div class="input-field">
            <i class="fas fa-lock"></i>
    <input type="text" name="direccion" placeholder="Dirección" maxlength="100" id="id_direccion">
          </div>
     <div class="input-field">
            <i class="fas fa-lock"></i>
<input type="text" name="telefono" placeholder="Telefono" maxlength="10" id="id_telefono">
          </div>
                 <div class="input-field">
            <i class="fas fa-lock"></i>
<input type="text" name="nacionalidad" placeholder="Nacionalidad" class="form-control" maxlength="100" id="id_nacionalidad">
          </div>

   <!--  <div>
     <div class="input" id="loco1">
      {{ field }}
     </div>
     </div>-->
    </p>

   <div>
 {% for field in form %}
{% if form.errors %}
  {% for error in field.errors %}

                <small style="color: grey" style="color:#1D281F">
   <ul style="text-align:justify;">
       <li style="text-align:left">
            {{ error }}
       </li>
   </ul>



</small>
  {% if field.help_text %}
<!-- <small style="color: grey">{{ field.help_text }}</small>-->
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endfor %}
         </div>
                      <input type="submit" value="Registrar" class="btn solid" />
        </form>
      </div>
    </div>

    <div class="panels-container" >
      <div class="panel left-panel" >
        <div class="content" >
          <h3>Este es el Formulario de Registro </h3>
          <p>
      <div class="dairy-container">
    <svg version="1.1" class="dairy-phil" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="140" height="160" viewBox="0 0 140 160" xml:space="preserve">
      <path class="phil-body-color st0" d="" />
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 500" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414">
  <g id="Dog">
    <path id="Tail" d="M129.156 353.39s18.97 7.04 66.28-33.353c5.333-4.554 27.983-19.43 20.43-39.663-2.22-5.944 15.814 7.103 10.583 15.475-2.717 4.346 12.914-24.28 8.18-34.94-3.97-8.937.72 2.106 4.522 11.012 2.074 4.856 5.65 14.676 5.65 14.676s1.558-8.87 3.458-12.755c8.08-16.52 8.56-45.826 8.56-45.826s34.53 76.393-31.55 98.266c-41.662 13.79-49.972 26.412-94.348 34.125-11.243 1.954-1.766-7.017-1.766-7.017z" fill="black"/>
    <path d="M131.725 206.136c15.91.61 58.806-5.192 53.423 31.048-3.744 25.213-14.994 39.164-4.563 59.255 9.038 17.408 11.89 28.502 16.813 39.783 12.04 27.59 7.95 41.02-34.52 42.35-7.098.223-8.376-12.084-34.284-12.25-26.646-.17-28.198 5.037-41.466 12.25-32.497 17.668-43.528-14.408-34.09-37.053 4.095-9.828 8.038-23.522 19.154-39.427 13.176-18.852 7.358-47.174 2.518-64.91-10.754-39.405 37.482-31.795 57.015-31.047z" fill="#895F55"/>
    <path d="M78.91 359.963c0-4.394-36.124-11.16-36.124-11.16-3.456 0 .6 27.082.6 27.082 0 4.394 6.807 7.96 10.263 7.96h19c3.454 0 6.26-3.566 6.26-7.96v-15.922zM212.874 372.322s3.067-21.52-.347-21.52c0 0-35.898 4.952-35.898 9.573v16.747c0 4.622 2.77 8.374 6.185 8.374h20.194c3.413 0 9.864-8.552 9.864-13.174z" fill="#4D2B23"/>
    <g id="Left-Leg" fill="#4D2B23">
      <path d="M87.507 256.19c.434 12.968 2.035 4.475 6.184 77.12l.8 65.22-28.64.365-1.05-143.933 22.707 1.228z"/>
      <path d="M65.633 369.15c-5.63 12.8-17.054 35.035-12.244 42.042 4.81 7.008 34.444 5.705 41.1 0 6.657-5.703-1.163-34.223-1.163-34.223l-27.694-7.82z"/>
    </g>
    <g id="Right-Leg" fill="#4D2B23">
      <path d="M168.19 256.062c-3.435 27.338-3.145 44.915-4.84 70.866-1.395 21.39-2.25 50.462-4.228 71.335l28.632.86 3.156-143.896-22.72.835z"/>
      <path d="M160.58 376.31l25.496-7.16s18.27 34.87 13.122 41.843c-5.146 6.974-37.563 5.78-44 0-6.436-5.78 5.38-34.683 5.38-34.683z"/>
    </g>
    <path d="M131.563 117.794c12.363.332 35.983 38.303 51.203 80.91 18.005 50.406 24.254 107.3-13.8 116.045-29.504 6.78-40.665 26.83-40.665 26.83s-11.09-19.587-33.1-25.89c-86.718-24.838 7.642-198.668 36.363-197.896z" fill="#895F55"/>
    <path d="M131.053 108.91c12.27.33 35.705 38.294 50.803 80.9 17.86 50.4 24.05 107.292-13.72 116.045-29.285 6.786-40.367 26.84-40.367 26.84s-11.007-19.585-32.848-25.883c-86.066-24.82 7.624-198.67 36.13-197.903z" fill="#4D2B23"/>
    <g id="Head">
      <g id="Skull-and-Ears" fill="#895F55">
        <path d="M135.31 39.158c33.32 1.967 58.817 29.84 56.906 62.207-1.91 32.365-30.51 57.045-63.83 55.078-33.317-1.967-58.815-29.84-56.904-62.206 1.91-32.366 30.512-57.046 63.83-55.08z"/>
        <path d="M188.994 116.853c.778-13.172-21.524-23.568-35.064-24.368 0 0-51.37-2.97-52.575-2.917-13.232.576-30.083 8.22-30.796 20.293l7.894 63.116c.133 31.932 15.4 42.738 28.11 46.2 9.09 2.474 16.873 1.19 16.873 1.19 6.28 1.113 11.743 1.506 16.496 1.32 32.212-1.272 31.822-29.217 32.5-40.695l16.56-64.137z"/>
        <g id="Ears">
          <path id="left-ear" d="M124.95 59.473c-3.293-6.975-22.013-28.028-35.04-30.564-13.026-2.537-32.915 9.01-43.118 15.348-32.86 20.41-38.325 44.944-38.61 54.772-.288 9.828 30.263 60.24 34.55 60.084 4.288-.156 3.494-70.25 28.584-90.82 6.18-5.065 32.668 1.847 38.364 2.465 5.695.617 18.035-5.438 15.27-11.287z"/>
          <path d="M162.154 69.546c-9.546-1.272-9.677-23.323 10.346-22.146 20.022 1.176 48.342 12.133 58.256 23.668 55.89 65.025-26.567 97.89-32.823 96.68-6.255-1.214 27.045-49.51-11.378-82.854-6.76-5.866-14.855-14.075-24.4-15.348z"/>
        </g>
        <path d="M71.957 86.188c-.397 6.725-12.75 21.59-16.78 30.163-1.47 3.13 8.052-1.97 10.348.612 1.978 2.227 7.05 5.48 8.79 7.442 1.373 1.545.695 7.01 3.18 4.804M188.987 78.74c-.93 7.63-1.673 23.65 1.604 30.606 1.113 2.358 8.324 15.485 8.318 15.49-2.895 2.573-9.01 3.65-11.906 6.22-1.1.978-1.834 6.816-3.857 6.697M106.182 53.71c10.57-18.07 9.962-51.505 43.24-44.827 1.276.256-2.645.204-3.843.708-2.18.917-4.173 2.763-5.96 4.323-6.133 5.36-7.064 11.24-10.514 17.14-.65 1.11-1.167 3.67-1.167 3.67s1.902-1.255 2.95-1.695c8.02-3.373 13.762-6.666 23.17-6.11l3.788.223s-1.97-.533-2.84-.167c-3.266 1.373-19.53 14.11-16.254 17.736.608.673 11.374-2.134 13.424-2.013l1.894.112s-2.15.11-2.896.763c-3.06 2.672-17.69 12.174-15.14 14.997"/>
      </g>
      <path id="Nose" d="M125.393 190.23c5.084-8.277 14.243-7.736 18.57-3.192s4.874 13.838-1.262 21.37c-12.175 14.945-27.178 9.444-36.633-2.163-6.135-7.532-3.57-17.366 1.262-21.37 4.83-4.003 13.99-3.462 18.063 5.356z" fill="black"/>
      <g id="Eyes">
        <path d="M160.1 94.853c7.51.444 13.135 8.79 12.554 18.626-.58 9.836-7.15 17.462-14.658 17.02-7.51-.445-13.135-8.79-12.554-18.627.58-9.837 7.15-17.463 14.658-17.02zM102.99 91.482c7.51.443 13.136 8.79 12.555 18.626-.58 9.836-7.15 17.462-14.658 17.02-7.51-.444-13.135-8.79-12.554-18.627.58-9.836 7.15-17.462 14.658-17.018z" fill="#fff"/>
        <g id="pupils" fill="#895F55">
          <path d="M153.025 99.05c3.755.223 6.63 3.365 6.413 7.014-.215 3.65-3.438 6.432-7.193 6.21-3.755-.22-6.628-3.364-6.413-7.013.215-3.648 3.44-6.43 7.193-6.21zM95.917 95.68c3.754.22 6.628 3.364 6.412 7.013-.216 3.65-3.44 6.43-7.194 6.21-3.755-.222-6.628-3.365-6.413-7.014.216-3.65 3.44-6.432 7.194-6.21z"/>
        </g>
      </g>
    </g>
  </g>
</svg>

      <path class="phil-arm-left st4" d="" />
      <path class="phil-arm-right st4" d="" />
      <path class="phil-leg-left st4" d="" />
      <path class="phil-leg-right st4" d="" />
    </svg>
    <span class="dairy-message" style="color:black">
        Para regresar al sitio Web  <span class="dairy-link"></span>

             <a class="dairy-link" href="{% url 'home' %}" >Home </a>
      <span class="dairy-close" style="color:white;background-color:green;padding-left:4px;">X</span>
    </span>
  </div>
          </p>


        </div>
      </div>
    </div>
  </div>


<!--
  <div class="container">

        <form method="post", enctype="multipart/form-data">
  <img class="avatar"alt="">

  <i class=" fas fa-user-circle" style="font-size: 90px;margin-right: 30%;color: #43914E"></i>
  <h2>Registro </h2>
  {% csrf_token %}
  {% for field in form %}


  {% if form.errors %}

  {% for error in field.errors %}
  <p style="color:#1D281F">{{ error }}</p>
  {% if field.help_text %}
  &lt;!&ndash; <small style="color: grey">{{ field.help_text }}</small> &ndash;&gt;
  {% endif %}
  {% endfor %}
  {% endif %}



    <p>
      <div class="input-div one">
        <div class="i">
          <i class="fas fa-user"></i>

          </div>

          <h5 style=" margin-top: 15px;
          font-size: 15px;
          color: #43914E;">
            {{ field.label_tag }}
          </h5>

        </div>
     <br>
     <div>
     <div class="input" id="loco1">
      {{ field }}
     </div>
     </div>
    </p>
  {% endfor %}
  <a  href="{% url 'login' %}"  style="margin-top: 5%;">Iniciar Sesion </a>


  <input class="btn" type="submit" value="Continuar">



</form>

&lt;!&ndash; {# Assumes you setup the password_reset view in your URLconf #} &ndash;&gt;

  </div>

-->

</body>
<script>
    var dairyClose = document.getElementsByClassName('dairy-close')[0];
var dairyMessage = document.getElementsByClassName('dairy-message')[0];
var philArmLeft = document.getElementsByClassName('phil-arm-left')[0];
var phil = document.getElementsByClassName('dairy-phil')[0];
var dairyPosition = document.getElementsByClassName('dairy-position')[0];

dairyClose.addEventListener('click', function() {

  dairyMessage.textContent = 'Gracias Por visitarnos';
  philArmLeft.classList.add('exit-wave');
  phil.classList.add('dairy-phil-exit');

  setTimeout(function(){
    dairyMessage.style.display = 'none';
    dairyPosition.style.display = 'none';
  }, 800);

}, false);
</script>

<script type="text/javascript" src="js/main.js"></script>

</html>